config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists do
  resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, presence: true, uniqueness: { scope: :list }

end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: true, uniqueness: true
  has_many :bookmarks
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: 'List was successfully created'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-m-4">
    </div>
    <div class="col col-m-4 mt-5">
      <h1>Add a Bookmark</h1>

      <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie%>
      <%= f.submit%>
      <% end %>
    </div>
     <div class="col col-m-4">
     </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://static.vecteezy.com/system/resources/thumbnails/004/796/030/small/illustration-graphic-of-popcorn-logo-free-vector.jpg" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to 'New List', new_list_path %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1471877325906-aee7c2240b5f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3270&q=80);">
  <div class="container">
    <h1>Save any kind of  <strong>movies </strong>!</h1>
    <p>Pick your choice from a variety of movies genres </p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>

<form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
</form>


 <h1>Created Lists </h1><%@lists. each do |list| %>

  <li> <%=link_to list.name, list_path(list) %> </li>
    <%end%>
    <div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://cdn.dnaindia.com/sites/default/files/styles/full/public/2021/09/14/996070-montylov-royaidnvbbu-unsplash.jpg)">
  Thriller </div>


  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://pbblogassets.s3.amazonaws.com/uploads/2015/03/header-image-337757.jpg)">
    Documentaries
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://miro.medium.com/max/500/1*xDIevNE7HEMiJQVTYg0qDQ.png)">
    Comedies
  </div>
</div>


<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>



<!--


          ! to understand link to.
<ul>
<li><%= link_to "add new list", new_list_path %></li>
</ul>



          ! to understand params
<form action= "lists/new" method ="get">
<input type ="text" name="member" placeholder= "what movie are you looking for?">
<input type= "submit">
</form>


-->

app/views/lists/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://static.vecteezy.com/system/resources/thumbnails/004/796/030/small/illustration-graphic-of-popcorn-logo-free-vector.jpg" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to 'Back Home', lists_path %>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>
<%#
<h1>New List</h1>
<%= render 'form', list: @list %>




<div class="container">
  <div class="row">
    <div class="col col-m-4">
    </div>
    <div class="col col-m-4 mt-5">
      <h1>Add a list</h1>

      <%= simple_form_for [@list] do |f| %>
      <%= f.input :name %>
      <%= f.input :name, as: :file, label: "Background"%>
      <%= f.button :submit, "Finished", class: "btn btn-primary mt-3" %>
      <% end %>
    </div>
     <div class="col col-m-4">
     </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col col-m-4">
    </div>
    <div class="col col-m-4 mt-5">

<% @list.movies.each do |movie| %>
  <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
  <%= movie.title %> - <%= movie.rating %>
  <%= movie.overview %>
  <%= image_tag movie.poster_url %>
  <%= link_to "Delete", bookmark_path(bookmark), method: :delete, data: {:confirm => "You sure?" } %>
<% end %>

<div class="container lists">
    <h1><%= @list.name %></h1>
  <div class="d-flex justify-content-between my-4">
    <div>
      <%= link_to 'add a bookmark', new_list_bookmark_path(@list), class: 'btn form-actions' %>
    </div>
  </div>